[package]
name = "raytracing-optix"
version = "0.1.0"
edition = "2024"

[dependencies]
raytracing = { workspace = true }
image = { workspace = true }
tracing = { workspace = true }

[build-dependencies]
cmake = "0.1"
bindgen = "0.72.1"